name: ArcaneServer
version: '1.0-SNAPSHOT'
main: net.herobrinetg.arcaneServer.ArcaneServer
api-version: '1.21'
authors: [ HerobrineTG ]
description: The Backend server plugin for the Arcane SMP
commands:
  arcaneserver:
    usage: /<command>
